In [36]:
import numpy as np

print(np.__version__)

1.19.4


In [39]:
a = np.array([1, 2, 3, 4]).reshape(2,2)
b = a.reshape(2,2)
print(a)
print(b)
print(a@a)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[ 7 10]
 [15 22]]


In [42]:
import scipy
scipy.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
